version: "3.7"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres-rsoi
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - database-network

  car-service:
    build:
      context: .
      dockerfile: car-service.Dockerfile
    image: stormurinn/car-service:v1.1
    container_name: car-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - database-network

  payment-service:
    build:
      context: .
      dockerfile: payment-service.Dockerfile
    image: stormurinn/payment-service:v1.1
    container_name: payment-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    networks:
      - database-network

  rental-service:
    build:
      context: .
      dockerfile: rental-service.Dockerfile
    image: stormurinn/rental-service:v1.1
    container_name: rental-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    networks:
      - database-network

  gateway-service:
    build:
      context: .
      dockerfile: gateway-service.Dockerfile
    image: stormurinn/gateway-service:v1.1
    container_name: gateway-service
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - car-service
      - payment-service
      - rental-service
    networks:
      - database-network

networks:
  database-network:
    name: database-network
    driver: bridge

volumes:
  db-data: